name: unstable

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: workspacer-build
        path: .\src\workspacer\bin\Release\net5.0-windows\win10-x64
    - name: Publish installer
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install wixtoolset
        .\scripts\buildinstaller.ps1 -buildDir .\src\workspacer\bin\Release\net5.0-windows\win10-x64\
    - uses: actions/upload-artifact@v2
      with:
        name: workspacer-installer
        path: .\out\workspacer.msi
    - name: Zip build output
      run: Compress-Archive -Path .\src\workspacer\bin\Release\net5.0-windows\win10-x64\* -DestinationPath .\out\workspacer-unstable-latest.zip
    - uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
       delete_release: true
       tag_name: Unstable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Unstable"
        prerelease: true
        files: |
          out/workspacer-unstable-latest.zip
          out/workspacer.msi
